// Generated by https://quicktype.io

export interface SeedUF {
  id: number
  nombreIndicador: NombreIndicador
  codigoIndicador: CodigoIndicador
  unidadMedidaIndicador: UnidadMedidaIndicador
  valorIndicador: number
  fechaIndicador: string
  tiempoIndicador: null
  origenIndicador: string
}
type NombreIndicador =
  | 'BITCOIN'
  | 'DÓLAR OBSERVADO'
  | 'EURO'
  | 'IMACEC'
  | 'INDICE DE PRECIOS AL CONSUMIDOR (IPC)'
  | 'INDICE DE VALOR PROMEDIO (IVP)'
  | 'LIBRA DE COBRE'
  | 'TASA DE DESEMPLEO'
  | 'TASA POLÍTICA MONETARIA (TPM)'
  | 'UNIDAD DE FOMENTO (UF)'
  | 'UNIDAD TRIBUTARIA MENSUAL (UTM)'
type CodigoIndicador =
  | 'BITCOIN'
  | 'DOLAR'
  | 'EURO'
  | 'IPC'
  | 'IMACEC'
  | 'IVP'
  | 'LIBRA_COBRE'
  | 'TPM'
  | 'TASA_DESEMPLEO'
  | 'UF'
  | 'UTM'

export enum OrigenIndicador {
  MindicadorCl = 'mindicador.cl'
}
type UnidadMedidaIndicador = 'Dólar' | 'Pesos' | 'Porcentaje'
interface SeedData{
    data : SeedUF[]
}
export const initialData: SeedData = {
  data: [
    {
      id: 1,
      nombreIndicador: 'LIBRA DE COBRE',
      codigoIndicador: 'LIBRA_COBRE',
      unidadMedidaIndicador: 'Dólar',
      valorIndicador: 3.56,
      fechaIndicador: '2021-01-04',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 2,
      nombreIndicador: 'EURO',
      codigoIndicador: 'EURO',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 873.3,
      fechaIndicador: '2021-01-04',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 3,
      nombreIndicador: 'DÓLAR OBSERVADO',
      codigoIndicador: 'DOLAR',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 710.95,
      fechaIndicador: '2021-01-04',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 4,
      nombreIndicador: 'TASA POLÍTICA MONETARIA (TPM)',
      codigoIndicador: 'TPM',
      unidadMedidaIndicador: 'Porcentaje',
      valorIndicador: 0.5,
      fechaIndicador: '2021-01-04',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 5,
      nombreIndicador: 'UNIDAD TRIBUTARIA MENSUAL (UTM)',
      codigoIndicador: 'UTM',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 50978.0,
      fechaIndicador: '2020-01-01',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 6,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29061.89,
      fechaIndicador: '2021-01-09',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 7,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29062.83,
      fechaIndicador: '2021-01-08',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 8,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29063.76,
      fechaIndicador: '2021-01-07',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 9,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29064.7,
      fechaIndicador: '2021-01-06',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 10,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29065.64,
      fechaIndicador: '2021-01-05',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 11,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29066.58,
      fechaIndicador: '2021-01-04',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 12,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29067.52,
      fechaIndicador: '2020-01-03',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 13,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29068.46,
      fechaIndicador: '2020-01-02',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 14,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29069.39,
      fechaIndicador: '2020-01-01',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 15,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30249.27,
      fechaIndicador: '2021-01-09',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 16,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30247.05,
      fechaIndicador: '2021-01-08',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 17,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30244.83,
      fechaIndicador: '2021-01-07',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 18,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30242.61,
      fechaIndicador: '2021-01-06',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 19,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30240.39,
      fechaIndicador: '2021-01-05',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 20,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30238.17,
      fechaIndicador: '2021-01-04',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 21,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30235.95,
      fechaIndicador: '2020-01-03',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 22,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30233.73,
      fechaIndicador: '2020-01-02',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 23,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30231.51,
      fechaIndicador: '2020-01-01',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 24,
      nombreIndicador: 'BITCOIN',
      codigoIndicador: 'BITCOIN',
      unidadMedidaIndicador: 'Dólar',
      valorIndicador: 32195.46,
      fechaIndicador: '2020-01-02',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 25,
      nombreIndicador: 'LIBRA DE COBRE',
      codigoIndicador: 'LIBRA_COBRE',
      unidadMedidaIndicador: 'Dólar',
      valorIndicador: 3.51,
      fechaIndicador: '2021-01-05',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 26,
      nombreIndicador: 'EURO',
      codigoIndicador: 'EURO',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 861.65,
      fechaIndicador: '2021-01-05',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 27,
      nombreIndicador: 'DÓLAR OBSERVADO',
      codigoIndicador: 'DOLAR',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 702.93,
      fechaIndicador: '2021-01-05',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 28,
      nombreIndicador: 'TASA POLÍTICA MONETARIA (TPM)',
      codigoIndicador: 'TPM',
      unidadMedidaIndicador: 'Porcentaje',
      valorIndicador: 0.5,
      fechaIndicador: '2021-01-05',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 29,
      nombreIndicador: 'LIBRA DE COBRE',
      codigoIndicador: 'LIBRA_COBRE',
      unidadMedidaIndicador: 'Dólar',
      valorIndicador: 3.56,
      fechaIndicador: '2021-01-06',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 30,
      nombreIndicador: 'EURO',
      codigoIndicador: 'EURO',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 863.72,
      fechaIndicador: '2021-01-06',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 31,
      nombreIndicador: 'DÓLAR OBSERVADO',
      codigoIndicador: 'DOLAR',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 702.29,
      fechaIndicador: '2021-01-06',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 32,
      nombreIndicador: 'TASA POLÍTICA MONETARIA (TPM)',
      codigoIndicador: 'TPM',
      unidadMedidaIndicador: 'Porcentaje',
      valorIndicador: 0.5,
      fechaIndicador: '2021-01-06',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 33,
      nombreIndicador: 'LIBRA DE COBRE',
      codigoIndicador: 'LIBRA_COBRE',
      unidadMedidaIndicador: 'Dólar',
      valorIndicador: 3.63,
      fechaIndicador: '2021-01-07',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 34,
      nombreIndicador: 'EURO',
      codigoIndicador: 'EURO',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 856.2,
      fechaIndicador: '2021-01-07',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 35,
      nombreIndicador: 'DÓLAR OBSERVADO',
      codigoIndicador: 'DOLAR',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 696.18,
      fechaIndicador: '2021-01-07',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 36,
      nombreIndicador: 'TASA POLÍTICA MONETARIA (TPM)',
      codigoIndicador: 'TPM',
      unidadMedidaIndicador: 'Porcentaje',
      valorIndicador: 0.5,
      fechaIndicador: '2021-01-07',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 37,
      nombreIndicador: 'BITCOIN',
      codigoIndicador: 'BITCOIN',
      unidadMedidaIndicador: 'Dólar',
      valorIndicador: 34046.67,
      fechaIndicador: '2021-01-05',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 38,
      nombreIndicador: 'LIBRA DE COBRE',
      codigoIndicador: 'LIBRA_COBRE',
      unidadMedidaIndicador: 'Dólar',
      valorIndicador: 3.64,
      fechaIndicador: '2021-01-08',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 39,
      nombreIndicador: 'EURO',
      codigoIndicador: 'EURO',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 870.41,
      fechaIndicador: '2021-01-08',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 40,
      nombreIndicador: 'DÓLAR OBSERVADO',
      codigoIndicador: 'DOLAR',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 709.99,
      fechaIndicador: '2021-01-08',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 41,
      nombreIndicador: 'TASA POLÍTICA MONETARIA (TPM)',
      codigoIndicador: 'TPM',
      unidadMedidaIndicador: 'Porcentaje',
      valorIndicador: 0.5,
      fechaIndicador: '2021-01-08',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 42,
      nombreIndicador: 'LIBRA DE COBRE',
      codigoIndicador: 'LIBRA_COBRE',
      unidadMedidaIndicador: 'Dólar',
      valorIndicador: 3.7,
      fechaIndicador: '2021-01-11',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 43,
      nombreIndicador: 'EURO',
      codigoIndicador: 'EURO',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 872.19,
      fechaIndicador: '2021-01-11',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 44,
      nombreIndicador: 'DÓLAR OBSERVADO',
      codigoIndicador: 'DOLAR',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 713.28,
      fechaIndicador: '2021-01-11',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 45,
      nombreIndicador: 'TASA POLÍTICA MONETARIA (TPM)',
      codigoIndicador: 'TPM',
      unidadMedidaIndicador: 'Porcentaje',
      valorIndicador: 0.5,
      fechaIndicador: '2021-01-11',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 46,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29149.08,
      fechaIndicador: '2021-02-09',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 47,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29146.26,
      fechaIndicador: '2021-02-08',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 48,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29143.44,
      fechaIndicador: '2021-02-07',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 49,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29140.63,
      fechaIndicador: '2021-02-06',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 50,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29137.81,
      fechaIndicador: '2021-02-05',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 51,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29135.0,
      fechaIndicador: '2021-02-04',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 52,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29132.18,
      fechaIndicador: '2021-02-03',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 53,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29129.37,
      fechaIndicador: '2021-02-02',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 54,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29126.55,
      fechaIndicador: '2021-02-01',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 55,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29123.74,
      fechaIndicador: '2021-01-31',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 56,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29120.92,
      fechaIndicador: '2021-01-30',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 57,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29118.11,
      fechaIndicador: '2021-01-29',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 58,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29115.3,
      fechaIndicador: '2021-01-28',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 59,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29112.48,
      fechaIndicador: '2021-01-27',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 60,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29109.67,
      fechaIndicador: '2021-01-26',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 61,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29106.86,
      fechaIndicador: '2021-01-25',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 62,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29104.04,
      fechaIndicador: '2021-01-24',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 63,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29101.23,
      fechaIndicador: '2021-01-23',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 64,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29098.42,
      fechaIndicador: '2021-01-22',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 65,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29095.61,
      fechaIndicador: '2021-01-21',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 66,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29092.8,
      fechaIndicador: '2021-01-20',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 67,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29089.99,
      fechaIndicador: '2021-01-19',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 68,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29087.18,
      fechaIndicador: '2021-01-18',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 69,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29084.36,
      fechaIndicador: '2021-01-17',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 70,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29081.55,
      fechaIndicador: '2021-01-16',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 71,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29078.74,
      fechaIndicador: '2021-01-15',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 72,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29075.93,
      fechaIndicador: '2021-01-14',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 73,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29073.13,
      fechaIndicador: '2021-01-13',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 74,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29070.32,
      fechaIndicador: '2021-01-12',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 75,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29067.51,
      fechaIndicador: '2021-01-11',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 76,
      nombreIndicador: 'UNIDAD DE FOMENTO (UF)',
      codigoIndicador: 'UF',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 29064.7,
      fechaIndicador: '2021-01-10',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 77,
      nombreIndicador: 'LIBRA DE COBRE',
      codigoIndicador: 'LIBRA_COBRE',
      unidadMedidaIndicador: 'Dólar',
      valorIndicador: 3.68,
      fechaIndicador: '2021-01-12',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 78,
      nombreIndicador: 'EURO',
      codigoIndicador: 'EURO',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 874.77,
      fechaIndicador: '2021-01-12',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 79,
      nombreIndicador: 'DÓLAR OBSERVADO',
      codigoIndicador: 'DOLAR',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 718.89,
      fechaIndicador: '2021-01-12',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 80,
      nombreIndicador: 'TASA POLÍTICA MONETARIA (TPM)',
      codigoIndicador: 'TPM',
      unidadMedidaIndicador: 'Porcentaje',
      valorIndicador: 0.5,
      fechaIndicador: '2021-01-12',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 81,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30338.5,
      fechaIndicador: '2021-02-09',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 82,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30335.62,
      fechaIndicador: '2021-02-08',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 83,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30332.74,
      fechaIndicador: '2021-02-07',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 84,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30329.86,
      fechaIndicador: '2021-02-06',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 85,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30326.98,
      fechaIndicador: '2021-02-05',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 86,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30324.09,
      fechaIndicador: '2021-02-04',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 87,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30321.21,
      fechaIndicador: '2021-02-03',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 88,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30318.33,
      fechaIndicador: '2021-02-02',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 89,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30315.45,
      fechaIndicador: '2021-02-01',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 90,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30312.57,
      fechaIndicador: '2021-01-31',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 91,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30309.69,
      fechaIndicador: '2021-01-30',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 92,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30306.81,
      fechaIndicador: '2021-01-29',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 93,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30303.93,
      fechaIndicador: '2021-01-28',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 94,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30301.05,
      fechaIndicador: '2021-01-27',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 95,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30298.17,
      fechaIndicador: '2021-01-26',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 96,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30295.29,
      fechaIndicador: '2021-01-25',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 97,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30292.42,
      fechaIndicador: '2021-01-24',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 98,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30289.54,
      fechaIndicador: '2021-01-23',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 99,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30286.66,
      fechaIndicador: '2021-01-22',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 100,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30283.78,
      fechaIndicador: '2021-01-21',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 101,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30280.9,
      fechaIndicador: '2021-01-20',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 102,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30278.03,
      fechaIndicador: '2021-01-19',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 103,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30275.15,
      fechaIndicador: '2021-01-18',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 104,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30272.27,
      fechaIndicador: '2021-01-17',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
    {
      id: 105,
      nombreIndicador: 'INDICE DE VALOR PROMEDIO (IVP)',
      codigoIndicador: 'IVP',
      unidadMedidaIndicador: 'Pesos',
      valorIndicador: 30269.4,
      fechaIndicador: '2021-01-16',
      tiempoIndicador: null,
      origenIndicador: 'mindicador.cl'
    },
  ]
}
